<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cuser\Module'                        => __DIR__ . '/Module.php',
    'Cuser\Controller\AdminController' => __DIR__ . '/src/Cuser/Controller/AdminController.php',
    'CuserTest\Framework\TestCase'        => __DIR__ . '/tests/Cuser/Framework/TestCase.php',
    'CuserTest\SampleTest'                => __DIR__ . '/tests/Cuser/SampleTest.php',
);
